export const CART_ACTION_TYPES = {
    SET_NEW_CART_ITEMS: 'cart/SET_NEW_CART_ITEMS',
    SET_IS_CART_OPEN: 'cart/SET_IS_CART_OPEN',
    SET_TOTAL_QUANTITY: 'cart/SET_TOTAL_QUANTITY',
    SET_TOTAL_PRICE:'cart/SET_TOTAL_PRICE'

}